src/forms/alert.py
"""Order forms"""
# pylint: disable=arguments-differ, invalid-name, super-with-arguments


from datetime import date

from flask_wtf import FlaskForm as Form
from wtforms import StringField, SelectField, FloatField, DateField
from wtforms.validators import DataRequired

from src.market import get_business_day
from src.forms.validators import (
    DateIfRequired,
    FutureDate,
    Underlying,
    Ticker,
    Location,
    WatchlistTicker,
)

date_time_format = "%Y-%m-%d"
operator_choices = [
    ("Up", "Up"),
    ("Up or Equal", "Up or Equal"),
    ("Down", "Down"),
    ("Down or Equal", "Down or Equal"),
]

signal_choices = [
    ("Price Signal", "Price Signal"),
    ("Daily Return Signal", "Daily Return Signal"),
    ("Limit Return Signal", "Limit Return Signal"),
    ("Portfolio Value Signal", "Portfolio Value Signal"),
    ("Daily Portfolio Return Signal", "Daily Portfolio Return Signal"),
]


class AddAlertForm(Form):
    """Form a signal alert form object."""

    signal = SelectField(u"Signal", default="Price Signal", choices=signal_choices)
    underlying = StringField(u"Underlying", [DataRequired(), Underlying()])
    operator = SelectField(u"Operator", default="Up", choices=operator_choices)
    target = FloatField(u"Target", [DataRequired()])
    start_date = DateField(
        u"Limit Date",
        [DateIfRequired(), FutureDate()],
        default=get_business_day(date.today()),
        format=date_time_format,
    )


class AddMarketWatchInstrument(Form):
    """Form an add marketwatch instrument form."""

    symbol = StringField(
        u"Ticker", [DataRequired(), Ticker(), Location(), WatchlistTicker()]
    )

src/views/alert.py
"""Alert endpoints"""

from typing import Union
from flask import Blueprint, url_for, render_template, redirect, flash
from flask_login import login_required, current_user

from src.forms import AddAlertForm, AddMarketWatchInstrument
from src.environment import User, MarketAlert, WatchListInstrument
from src.market import Instrument, Symbol, get_instrument
from src.market.ref_data import up, down, up_equal, down_equal
from src.market.signal import (
    Signal,
    DailyPortfolioReturnSignal,
    DailyReturnSignal,
    PriceSignal,
    LimitReturnSignal,
    PortfolioValueSignal,
)


alert_blueprint = Blueprint("alert", __name__, url_prefix="/alert")


@alert_blueprint.route("/list", methods=["GET"])
@login_required
def list_alerts():
    """List alerts."""

    user: User = current_user
    return render_template("alert/list_alerts.html", alerts=user.market_alerts)


@alert_blueprint.route("/add_alert", methods=["GET", "POST"])
@login_required
def add_alert():
    """Add new alert."""

    user: User = current_user
    alert_form = AddAlertForm()

    if alert_form.validate_on_submit():
        signal = get_signal(
            alert_form.signal.data,
            alert_form.underlying.data,
            alert_form.operator.data,
            alert_form.target.data,
            alert_form.start_date.data,
        )

        if signal not in [alert.signal for alert in user.market_alerts]:
            user.add_market_alert(MarketAlert(signal))
            return redirect(url_for("alert.list_alerts"))
        flash("Market alert already exists, please activate it.", "danger")

    return render_template("alert/add_alert.html", form=alert_form)


@alert_blueprint.route("/deactivate_alert/<int:alert_id>", methods=["GET"])
@login_required
def deactivate_alert(alert_id):
    """Deactivate alert."""

    alert = MarketAlert.find_by_id(alert_id)
    alert.deactivate()
    return redirect(url_for("alert.list_alerts"))


@alert_blueprint.route("/activate_alert/<int:alert_id>", methods=["GET"])
@login_required
def activate_alert(alert_id):
    """Activate alert."""

    alert = MarketAlert.find_by_id(alert_id)
    alert.activate()
    return redirect(url_for("alert.list_alerts"))


@alert_blueprint.route("/delete_alert/<int:alert_id>", methods=["GET"])
@login_required
def delete_alert(alert_id):
    """Delete alert."""

    alert = MarketAlert.find_by_id(alert_id)
    alert.delete_from_db()
    return redirect(url_for("alert.list_alerts"))


@alert_blueprint.route("/watchlist", methods=["GET", "POST"])
@login_required
def list_watchlist():
    """List alert."""

    user: User = current_user
    form = AddMarketWatchInstrument()

    if form.validate_on_submit():
        watchlist_inst = WatchListInstrument(get_instrument(Symbol(form.symbol.data)))
        user.add_watchlist_instrument(watchlist_inst)
        return redirect(url_for("alert.list_watchlist"))

    return render_template(
        "alert/watchlist.html", instruments=user.watch_list, form=form
    )


@alert_blueprint.route("/delete_watchlist/<int:inst_id>", methods=["GET"])
@login_required
def delete_watchlist_instrument(inst_id):
    """Delete watchlist instrument."""

    watchlist_inst = WatchListInstrument.find_by_id(inst_id)
    watchlist_inst.delete_from_db()
    return redirect(url_for("alert.list_watchlist"))


def get_signal(
    signal: str, underlying: Union[Instrument, str], operator, target, start_date
) -> Signal:
    """Get underlying portfolio or instrument."""

    operator_dict = {
        "Up": up,
        "Up or Equal": up_equal,
        "Down": down,
        "Down or Equal": down_equal,
    }
    operator = operator_dict[operator]
    signal_dict = {
        "Price Signal": lambda: PriceSignal(
            get_instrument(Symbol(underlying)), operator, target
        ),
        "Daily Return Signal": lambda: DailyReturnSignal(
            get_instrument(Symbol(underlying)), operator, target
        ),
        "Limit Return Signal": lambda: LimitReturnSignal(
            get_instrument(Symbol(underlying)), operator, target, start_date
        ),
        "Portfolio Value Signal": lambda: PortfolioValueSignal(
            underlying, operator, target
        ),
        "Daily Portfolio Return Signal": lambda: DailyPortfolioReturnSignal(
            underlying, operator, target
        ),
    }

    func = signal_dict[signal]
    return func()

src/templates/alert/add_alert.html
{% extends "base/portfolio.html" %}
{% block content %}

<div class="container mt-5">

    <form class="card p-3 bg-light" action="{{ url_for('alert.add_alert') }}" method="post">
        <legend class="mb-3">Add new alert:</legend>

        {{ form.hidden_tag() }}
        {% for field in form %}
        <div class="row 3 align-items-center mt-2">
            {% if field.errors %}
            {% for e in field.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            <div class="col-2">
                {% if field.widget.input_type != 'hidden' %} {{ field.label }} {% endif %}
            </div>
            <div class="col-sm-1">
                {{ field }}
            </div>
        </div>
        {% endfor %}

        <div>
            <button type="submit" class="btn btn-success mt-2">Submit</button>
        </div>

    </form>
</div>

{% endblock %}

src/templates/alert/list_alerts.html
{% extends "base/portfolio.html" %}
{% block content %}

{% import 'alert/macro.html' as macro_file -%}

<div class="container mt-5">
    <h2 class="text-success">
        Market Alerts:
    </h2>

</div>

<div class="container mt-4 mb-3">
    <div class="card">
        <div class="row">
            <div class="col-12">
                <div class="card-body">

                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home"
                                type="button" role="tab" aria-controls="home" aria-selected="true">Active
                                Alerts</button>
                        </li>
                        <li class="nav-item">
                            <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile"
                                type="button" role="tab" aria-controls="profile" aria-selected="false">Inactive
                                Alerts</button>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            {{ macro_file.get_alert_table(True, alerts) }}
                        </div>
                        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            {{ macro_file.get_alert_table(False, alerts) }}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

src/templates/alert/macro.html
{% macro get_alert_table(status, alerts) -%}

<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th scope="col">Signal type</th>
                    <th scope="col">Underlying</th>
                    <th scope="col">Operator</th>
                    <th scope="col">Target</th>
                    <th scope="col">Creation Date</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for alert in alerts if alert.active == status %}
                <tr class="text-center">
                    <td class="align-middle">{{ alert.signal.signal_type }}</td>
                    <td class="align-middle">{{ alert.signal.underlying }}</td>
                    <td class="align-middle">{{ alert.signal.operator }}</td>
                    <td class="align-middle">{{ alert.signal.target }}</td>
                    <td class="align-middle">{{ alert.signal.creation_date }}</td>
                    <td class="align-middle">{{ render_alert_options(alert.id, alert.active) }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{%- endmacro -%}

{% macro render_alert_options(alert_id, status) -%}
{% if status %}
<a href="{{ url_for('alert.deactivate_alert', alert_id=alert_id) }}" class="btn btn-outline-success">Deactivate
    Alert</a>
{% else %}
<a href="{{ url_for('alert.activate_alert', alert_id=alert_id) }}" class="btn btn-outline-success">Activate
    Alert</a>
{% endif %}
<a href="{{ url_for('alert.delete_alert', alert_id=alert_id) }}" class="btn btn-outline-danger">Delete
    Alert</a>
{%- endmacro -%}

{% macro get_watchlist_table(instruments) -%}

<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th scope="col">Symbol</th>
                    <th scope="col">Name</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for instrument in instruments %}
                <tr class="text-center">
                    <td class="align-middle">{{ instrument.instrument.symbol }}</td>
                    <td class="align-middle">{{ instrument.instrument.name }}</td>
                    <td class="align-middle">
                        <a href="{{ url_for('alert.delete_watchlist_instrument', inst_id=instrument.id) }}"
                            class="btn btn-outline-danger">Delete Ticker
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{%- endmacro -%}

src/templates/alert/watchlist.html
{% extends "base/portfolio.html" %}
{% block content %}
{% import 'alert/macro.html' as macro_file -%}

<div class="container mt-5">
    <h2 class="text-success">Watchlist:</h2>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-danger" role="alert">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
</div>
<div class="container mt-4">

    <div class="card">
        <div class="row">
            <div class="col-8">
                <div class="container mt-4">
                    {{ macro_file.get_watchlist_table(instruments) }}
                </div>
            </div>
            <div class="col 4">
                <div class="row justify-content-center mt-4 mb-4">
                    <div class="col-10">
                        <div class="card">
                            <h5 class="card-header text-center bg-success text-white bg-gradient">
                                Add new ticker:
                            </h5>
                            <div class="card-body">
                                <div class="row justify-content-center">
                                    <div class="col-12">
                                        <form class="card p-3 bg-light" action="{{ url_for('alert.list_watchlist') }}"
                                            method="post">

                                            {{ form.hidden_tag() }}
                                            {% for field in form %}
                                            <div class="row 3 align-items-center mt-2">
                                                {% if field.errors %}
                                                {% for e in field.errors %}
                                                <p class="help-block">{{ e }}</p>
                                                {% endfor %}
                                                {% endif %}
                                                <div class="col-3">
                                                    {% if field.widget.input_type != "hidden" %} {{ field.label }}
                                                    {% endif %}
                                                </div>
                                                <div class="col-sm-1">
                                                    {{ field }}
                                                </div>
                                            </div>
                                            {% endfor %}
                                            <div>
                                                <button type="submit" class="btn btn-success mt-2">Submit</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}