src/models/portfolio.py
from pydantic.dataclasses import dataclass
from typing import List

from src.db import DB_Portfolio
from src.models.utils import (
    credential_check, 
    UserAlreadyRegisteredError, 
    UserNotFoundError, 
    InvalidEmailError, 
    IncorrectPasswordError, 
    PortfolioNotFoundError,
)

@dataclass
class Portfolio:
    name: str
    source: str
    status: str
    portfolio_type: str
    email: str
    portfolio_id: int
    questrade_id: int = None

    @classmethod
    def find_all(cls, email: str) -> List["Portfolio"]:
        port_list = DB_Portfolio.get_portfolio_list(email)
        if port_list is None:
            raise PortfolioNotFoundError("No portfolio exist in the database. Add a custom portfolio or update with Questrade.")
        return [cls(*port) for port in port_list]

    @classmethod
    def find_by_name(cls, name: str, email: str) -> "Portfolio":
        DB_Portfolio.get_portfolio(name, email)

    @staticmethod
    def add_portfolio(name: str, source: str, status: str, portfolio_type: str, email: str, portfolio_id: int) -> None:
        DB_Portfolio.add_portfolio(name, source, status, portfolio_type, email, portfolio_id)
    
    @staticmethod
    def update_portfolio(status: str, portfolio_type: str, name: str) -> None:
        DB_Portfolio.update_portfolio(status, portfolio_type, name)
    
    def delete(self) -> None:
        DB_Portfolio.delete_portfolio(self.email, self.name)




    

src/forms/portfolio.py
"""Portfolio forms"""

from flask_wtf import FlaskForm as Form
from wtforms import StringField, SelectField
from wtforms.validators import (
    DataRequired,
    Length,
)

from src.environment import Portfolio
from src.market import Currency
from src.market.types import PortfolioType
from src.forms.validators import PortfolioName, Ticker

port_type_choices = [
    (PortfolioType.custom, PortfolioType.custom),
    (PortfolioType.margin, PortfolioType.margin),
    (PortfolioType.tfsa, PortfolioType.tfsa),
    (PortfolioType.cash, PortfolioType.cash),
    (PortfolioType.rrsp, PortfolioType.rrsp),
]

currency_choices = [("CAD", Currency("CAD")), ("USD", Currency("USD"))]


class AddPortfolioForm(Form):
    """Add portfolio form."""

    port_name = StringField(
        u"Portfolio Name", [DataRequired(), Length(max=20), PortfolioName()]
    )
    port_type = SelectField(u"Portfolio Type", default=1, choices=port_type_choices)
    reporting_currency = SelectField(
        u"Reporting Currency", default=1, choices=currency_choices
    )
    benchmark = StringField(u"Benchmark", [DataRequired(), Ticker()], default="^GSPC")


def generate_edit_portfolio_form(portfolio: Portfolio) -> Form:
    """Function that generates an instance of EditPortfolioForm and sets default arguments."""

    class EditPortfolioForm(Form):
        """Edit portfolio form."""

        port_name = StringField(
            u"Portfolio Name",
            [DataRequired(), Length(max=20), PortfolioName(exclude=portfolio.name)],
            default=portfolio.name,
        )
        port_type = SelectField(
            u"Portfolio Type",
            choices=port_type_choices,
            default=portfolio.portfolio_type,
        )
        reporting_currency = SelectField(
            u"Reporting Currency",
            choices=currency_choices,
            default=portfolio.reporting_currency,
        )
        benchmark = StringField(
            u"Benchmark",
            [DataRequired(), Ticker()],
            default=portfolio.benchmark.symbol.symbol,
        )

    return EditPortfolioForm

src/views/order.py
"""Order endpoints"""

from flask import Blueprint, url_for, render_template, redirect
from flask_login import login_required
from flask_wtf import FlaskForm

from src.environment import Portfolio, Position, Order
from src.forms.order import AddOrderForm, generate_edit_order_form
from src.market import Symbol, SingleValue, get_instrument, DIRECTION_MAP

order_blueprint = Blueprint("order", __name__, url_prefix="/order")


@order_blueprint.route("/delete_order/<int:order_id>", methods=["GET"])
@login_required
def delete_order(order_id: int):
    """Delete an order."""

    order = Order.find_by_id(order_id)
    position = order.position
    order.delete_from_db()
    if not position.orders:
        position.delete_from_db()
    return redirect(url_for("portfolio.list_portfolios"))


@order_blueprint.route("/edit/<int:order_id>", methods=["GET", "POST"])
@login_required
def edit_order(order_id: int):
    """Edit an order."""
    order = Order.find_by_id(order_id)
    edit_form = generate_edit_order_form(order)
    form: FlaskForm = edit_form()
    if form.validate_on_submit():
        order.edit(
            form.quantity.data,
            DIRECTION_MAP[form.direction.data],
            SingleValue(form.cost.data, order.cost.currency),
            form.exec_datetime.data,
        )
        return redirect(url_for("portfolio.list_portfolios"))
    return render_template("order/edit_order.html", form=form, order_id=order_id)


@order_blueprint.route("/<int:portfolio_id>/add_order", methods=["GET", "POST"])
@login_required
def add_order(portfolio_id):
    """Add order."""

    form = AddOrderForm()
    if form.validate_on_submit():
        symbol = Symbol(form.symbol.data)
        instrument = get_instrument(symbol)
        port = Portfolio.find_by_id(portfolio_id)
        pos = port.get_position_by_symbol(symbol) or port.add_position(
            Position(instrument)
        )
        order = Order(
            form.quantity.data,
            DIRECTION_MAP[form.direction.data],
            SingleValue(form.cost.data, instrument.asset_currency),
            form.exec_datetime.data,
        )
        pos.add_order(order)
        return redirect(url_for("portfolio.list_portfolios"))
    return render_template("order/add_order.html", form=form, portfolio_id=portfolio_id)

src/views/portfolio.py
"""Portfolio endpoints"""

from flask import Blueprint, url_for, render_template, redirect, flash
from flask_login import login_required, current_user
from flask_wtf import FlaskForm

from src.environment import Portfolio
from src.market import Symbol, Currency, get_instrument
from src.forms.portfolio import AddPortfolioForm, generate_edit_portfolio_form


portfolio_blueprint = Blueprint("portfolio", __name__, url_prefix="/portfolio")


@portfolio_blueprint.route("/list", methods=["GET"])
@login_required
def list_portfolios():
    """List portfolios of the user including current market values."""

    portfolios = current_user.portfolios
    portfolios.sort(key=lambda x: x.primary, reverse=True)

    if not portfolios:
        flash("Add a custom portfolio!")

    return render_template("portfolio/list_portfolios.html", portfolios=portfolios)


@portfolio_blueprint.route("/add_portfolio", methods=["GET", "POST"])
@login_required
def add_portfolio():
    """Add a new portfolio."""

    form = AddPortfolioForm()
    if form.validate_on_submit():

        symbol = Symbol(form.benchmark.data)
        security = get_instrument(symbol)
        currency = Currency(form.reporting_currency.data)

        portfolio = Portfolio(
            form.port_name.data,
            form.port_type.data,
            currency,
            security,
        )
        current_user.add_portfolio(portfolio)

        if current_user.get_primary_portfolio() is None:
            portfolio.set_as_primary()
        return redirect(url_for("portfolio.list_portfolios"))
    return render_template("portfolio/add_portfolio.html", form=form)


@portfolio_blueprint.route("/edit/<int:portfolio_id>", methods=["GET", "POST"])
@login_required
def edit_portfolio(portfolio_id):
    """Edit an existing portfolio."""

    port = Portfolio.find_by_id(portfolio_id)
    edit_form = generate_edit_portfolio_form(port)
    form: FlaskForm = edit_form()
    if form.validate_on_submit():
        symbol = Symbol(form.benchmark.data)
        security = get_instrument(symbol)
        currency = Currency(form.reporting_currency.data)
        port.edit(
            form.port_name.data,
            currency,
            form.port_type.data,
            security,
        )
        return redirect(url_for("portfolio.list_portfolios"))
    return render_template(
        "portfolio/edit_portfolio.html", form=form, portfolio_id=portfolio_id
    )


@portfolio_blueprint.route("/delete/<int:portfolio_id>", methods=["GET"])
@login_required
def delete_portfolio(portfolio_id):
    """Delete an existing portfolio along with its positions as well as orders."""

    port = Portfolio.find_by_id(portfolio_id)
    port.delete_from_db()
    return redirect(url_for("portfolio.list_portfolios"))


@portfolio_blueprint.route("/set_primary/<int:portfolio_id>", methods=["GET"])
@login_required
def set_portfolio_primary(portfolio_id):
    """Set a portfolio primary which will be viewed at the top when listing portfolios."""

    primary_portfolio: Portfolio = current_user.get_primary_portfolio()

    if primary_portfolio:
        primary_portfolio.primary = False

    current_portfolio = Portfolio.find_by_id(portfolio_id)
    current_portfolio.set_as_primary()

    return redirect(url_for("portfolio.list_portfolios"))


@portfolio_blueprint.route("/activate_daily_report/<int:portfolio_id>", methods=["GET"])
@login_required
def activate_daily_report(portfolio_id):
    """Activate daily report for a given portfolio."""

    port = Portfolio.find_by_id(portfolio_id)
    port.daily_report.activate()

    return redirect(url_for("portfolio.list_portfolios"))


@portfolio_blueprint.route(
    "/deactivate_daily_report/<int:portfolio_id>", methods=["GET"]
)
@login_required
def deactivate_daily_report(portfolio_id):
    """Activate daily report for a given portfolio."""

    port = Portfolio.find_by_id(portfolio_id)
    port.daily_report.deactivate()

    return redirect(url_for("portfolio.list_portfolios"))

src/views/position.py
"""Position endpoints"""

from datetime import date
from flask import Blueprint, url_for, render_template, redirect
from flask_login import login_required

from src.environment import Position, Order
from src.market.utils import get_business_day
from src.market.ref_data import buy, sell


position_blueprint = Blueprint("position", __name__, url_prefix="/position")


@position_blueprint.route("/<int:position_id>/details", methods=["GET"])
@login_required
def position_details(position_id):
    """Get position details."""

    return render_template(
        "position/position_details.html",
        position=Position.find_by_id(position_id),
    )


@position_blueprint.route("/<int:position_id>/close", methods=["GET"])
@login_required
def close_position(position_id):
    """Close existing position by adding closing order."""

    position = Position.find_by_id(position_id)

    if position.is_open:
        order = Order(
            position.open_quantity,
            sell if position.open_quantity > 0 else buy,
            position.security.value(raw=True),
            get_business_day(date.today()),
        )
        position.add_order(order)

    return redirect(url_for("portfolio.list_portfolios"))

src/templates/portfolio/add_portfolio.html
{% extends "base/portfolio.html" %}
{% block content %}

<div class="container mt-5">

    <form class="card p-3 bg-light" action="{{ url_for('portfolio.add_portfolio') }}" method="post">
        <legend class="mb-3">Add new custom portfolio:</legend>

        {{ form.hidden_tag() }}
        {% for field in form %}
        <div class="row 3 align-items-center mt-2">
            {% if field.errors %}
            {% for e in field.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            <div class="col-2">
                {% if field.widget.input_type != 'hidden' %} {{ field.label }} {% endif %}
            </div>
            <div class="col-sm-1">
                {{ field }}
            </div>
        </div>
        {% endfor %}

        <div>
            <button type="submit" class="btn btn-success mt-2">Submit</button>
        </div>

    </form>
</div>

{% endblock %}

src/templates/portfolio/edit_portfolio.html
{% extends "base/portfolio.html" %}
{% block content %}

<div class="container mt-5">

    <form class="card p-3 bg-light" action="{{ url_for('portfolio.edit_portfolio', portfolio_id=portfolio_id)  }}"
        method="post">
        <legend class="mb-3">Edit portfolio:</legend>

        {{ form.hidden_tag() }}
        {% for field in form %}
        <div class="row 3 align-items-center mt-2">
            {% if field.errors %}
            {% for e in field.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            <div class="col-2">
                {% if field.widget.input_type != 'hidden' %} {{ field.label }} {% endif %}
            </div>
            <div class="col-sm-1">
                {{ field }}
            </div>
        </div>
        {% endfor %}

        <div>
            <button type="submit" class="btn btn-success mt-2">Submit</button>
        </div>

    </form>
</div>

{% endblock %}

src/templates/portfolio/list_portfolios.html
{% extends "base/portfolio.html" %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-success">
        My Portfolios:
    </h2>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-danger" role="alert">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}


</div>


{% for port in portfolios %}
<div class="container mt-4 mb-3">
    <div class="card">
        <h5 class="card-header">

            <div class="row">
                <div class="col-8">
                    Portfolio: {{ port.name }}
                </div>
                <div class="col-4 text-end">
                    Portfolio creation date: {{port.date.strftime('%Y-%m-%d') }}
                </div>
            </div>
        </h5>
        <div class="row">
            <div class="col-9">
                <div class="card-body">

                    <p class="card-text">Reporting currency: {{ port.reporting_currency }}</p>
                    <p class="card-text">Total market value: {{ port.current_value() }}</p>
                    <p class="card-text">Benchmark: {{ port.benchmark.symbol }}</p>

                    <div class="card">

                        <h6 class="card-header">
                            Open Positions
                        </h6>

                        <div class="card-body">

                            <table class="table">
                                <thead>
                                    <tr class="text-center">
                                        <th scope="col">Instrument Type</th>
                                        <th scope="col">Symbol</th>
                                        <th scope="col">Market Cap</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for position in port.positions if position.is_open %}
                                    <tr class="text-center">

                                        <td class="align-middle">{{ position.security.security_type }}</td>
                                        <td class="align-middle">{{ position.security.symbol }}</td>
                                        <td class="align-middle">{{ position.current_value() }}</td>
                                        <td class="align-middle">

                                            <a href="{{ url_for('position.position_details', position_id=position.id) }}"
                                                class="btn btn-outline-success">View details</a>
                                            <a href="{{ url_for('position.close_position', position_id=position.id) }}"
                                                class="btn btn-outline-danger">Close Position</a>

                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col align-self-center">
                <div class="row justify-content-center mt-4 mb-4">
                    <div class="col-10">
                        <div class="card">
                            <h5 class="card-header text-center bg-success text-white bg-gradient">
                                Actions
                            </h5>
                            <div class="card-body">
                                <div class="row justify-content-center">
                                    <div class="col-11">
                                        <ul class="list-group">
                                            {% if port.daily_report.active == False%}
                                            <a href="{{ url_for('portfolio.activate_daily_report', portfolio_id=port['id']) }}"
                                                class="btn btn-outline-success">Activate Daily Report</a>
                                            {% else %}
                                            <a href="{{ url_for('portfolio.deactivate_daily_report', portfolio_id=port['id']) }}"
                                                class="btn btn-outline-success">Deactivate Daily Report</a>
                                            {% endif %}
                                            {% if port.primary == False%}
                                            <a href="{{ url_for('portfolio.set_portfolio_primary', portfolio_id=port['id']) }}"
                                                class="btn btn-outline-success mt-2">Set Portfolio as Primary</a>
                                            {% endif %}
                                            <a href="{{ url_for('order.add_order', portfolio_id=port['id']) }}"
                                                class="btn btn-outline-success mt-2">Add Order</a>
                                            <a href="{{ url_for('portfolio.edit_portfolio', portfolio_id=port['id']) }}"
                                                class="btn btn-outline-success mt-2">Edit Portfolio</a>
                                            <a href="{{ url_for('portfolio.delete_portfolio', portfolio_id=port['id']) }}"
                                                class="btn btn-outline-danger mt-2">Delete Portfolio</a>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}
{% endblock %}

src/templates/portfolio/portfolio.html
{% extends "base/portfolio.html" %}
{% block content %}
    <div class="container mt-5">
        <h2 class="text-success">
            Positions of: {{ portfolio.name }}
        </h2>

        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
        {% endif %}
        
    </div>

    <!-- # TODO Move Delete to right, add icons near card headrs. ex questrade logo and cutom logo. -->
  
    <div class="container mt-4 mb-3">
      <div class="card"></div>
          <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Type</th>
                  <th scope="col">Symbol</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Price</th>
                  <th scope="col">Market Value (CAD)</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for position in position_list %}
                <tr>
                  <th scope="row">{{loop.index}}</th>
                  <td>Type</td>
                  <td>{{ position.symbol }}</td>
                  <td>{{ position.quantity }}</td>
                  <td>Price</td>
                  <td>Market Value</td>
                  <td>
                    <a href="{{ url_for('order.list_orders', portfolio_name=portfolio.name, symbol=position.symbol) }}" class="btn bg-warning">View Orders</a>
                  </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
      </div>
    </div>
    
    <div class="container mt-4 mb-3">
      <div class="col">
        <div class="card"></div>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Total Portolio Return</th>
                <th scope="col">Total Portfolio Market Value (CAD)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Price</td>
                <td>Market Value</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
{% endblock %}

src/templates/portfolio/portfolio_list.html
{% extends "base_portfolio.html" %}
{% block content %}
    <div class="container mt-5">
        <h2 class="text-success">
            Please choose a portfolio:
        </h2>
    </div>

    {% for portfolio in port_list %}
        <div class="container mt-5">
            <div class="card">
                <div class="card-header">
                    {{ portfolio.source }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">Portfolio name: {{ portfolio.name }}</h5>
                    <p class="card-text">Account status is {{ portfolio.status }} and type is {{ portfolio.portfolio_type }}.</p>
                    <a href="{{ url_for('portfolio.portfolio_overview') }}" class="btn bg-warning">View Portfolio</a>
                    <a href="{{ url_for('account.edit_portfolio', portfolio_id=portfolio.name) }}" class="btn bg-info">Edit Portfolio</a>
                    <a href="{{ url_for('portfolio.portfolio_overview', portfolio_id=portfolio[number]) }}" class="btn bg-danger text-white">Delete Portfolio</a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

src/templates/portfolio/portfolio_overview.html
{% extends "base_portfolio.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Portfolio Engineer/h1>
        <p class="lead">This is an app for portfolio performance monitoring and analysis.</p>
        <hr class="my-4">
        <p>Just sign up, and get started by linking your Questrade account. We'll do the rest!</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Get started</a></p>
    </div>
{% endblock %}

src/templates/portfolio/positions.html
{% extends "base/portfolio.html" %}
{% block content %}
    <div class="container mt-5">
        <h2 class="text-success">
            Positions of: {{ portfolio.name }}
        </h2>

        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
        {% endif %}
        
    </div>

    <!-- # TODO Move Delete to right, add icons near card headrs. ex questrade logo and cutom logo. -->
  
    <div class="container mt-4 mb-3">
      <div class="card"></div>
          <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Type</th>
                  <th scope="col">Symbol</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for position in position_list %}
                <tr>
                  <th scope="row">{{loop.index}}</th>
                  <td>Type</td>
                  <td>{{ position.symbol }}</td>
                  <td>{{ position.quantity }}</td>
                  <td>
                    <a href="{{ url_for('order.list_orders', portfolio_name=portfolio.name, symbol=position.symbol) }}" class="btn bg-warning">View Orders</a>
                  </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
      </div>
    </div>
{% endblock %}