src/models/portfolio.py
from pydantic.dataclasses import dataclass
from typing import List

from src.db import DB_Portfolio
from src.models.utils import (
    credential_check, 
    UserAlreadyRegisteredError, 
    UserNotFoundError, 
    InvalidEmailError, 
    IncorrectPasswordError, 
    PortfolioNotFoundError,
)

@dataclass
class Portfolio:
    name: str
    source: str
    status: str
    portfolio_type: str
    email: str
    portfolio_id: int
    questrade_id: int = None

    @classmethod
    def find_all(cls, email: str) -> List["Portfolio"]:
        port_list = DB_Portfolio.get_portfolio_list(email)
        if port_list is None:
            raise PortfolioNotFoundError("No portfolio exist in the database. Add a custom portfolio or update with Questrade.")
        return [cls(*port) for port in port_list]

    @classmethod
    def find_by_name(cls, name: str, email: str) -> "Portfolio":
        DB_Portfolio.get_portfolio(name, email)

    @staticmethod
    def add_portfolio(name: str, source: str, status: str, portfolio_type: str, email: str, portfolio_id: int) -> None:
        DB_Portfolio.add_portfolio(name, source, status, portfolio_type, email, portfolio_id)
    
    @staticmethod
    def update_portfolio(status: str, portfolio_type: str, name: str) -> None:
        DB_Portfolio.update_portfolio(status, portfolio_type, name)
    
    def delete(self) -> None:
        DB_Portfolio.delete_portfolio(self.email, self.name)




    

src/forms/portfolio.py
"""Portfolio forms"""

from flask_wtf import FlaskForm as Form
from wtforms import StringField, SelectField
from wtforms.validators import (
    DataRequired,
    Length,
)

from src.environment import Portfolio
from src.market import Currency
from src.market.types import PortfolioType
from src.forms.validators import PortfolioName, Ticker

port_type_choices = [
    (PortfolioType.custom, PortfolioType.custom),
    (PortfolioType.margin, PortfolioType.margin),
    (PortfolioType.tfsa, PortfolioType.tfsa),
    (PortfolioType.cash, PortfolioType.cash),
    (PortfolioType.rrsp, PortfolioType.rrsp),
]

currency_choices = [("CAD", Currency("CAD")), ("USD", Currency("USD"))]


class AddPortfolioForm(Form):
    """Add portfolio form."""

    port_name = StringField(
        u"Portfolio Name", [DataRequired(), Length(max=20), PortfolioName()]
    )
    port_type = SelectField(u"Portfolio Type", default=1, choices=port_type_choices)
    reporting_currency = SelectField(
        u"Reporting Currency", default=1, choices=currency_choices
    )
    benchmark = StringField(u"Benchmark", [DataRequired(), Ticker()], default="^GSPC")


def generate_edit_portfolio_form(portfolio: Portfolio) -> Form:
    """Function that generates an instance of EditPortfolioForm and sets default arguments."""

    class EditPortfolioForm(Form):
        """Edit portfolio form."""

        port_name = StringField(
            u"Portfolio Name",
            [DataRequired(), Length(max=20), PortfolioName(exclude=portfolio.name)],
            default=portfolio.name,
        )
        port_type = SelectField(
            u"Portfolio Type",
            choices=port_type_choices,
            default=portfolio.portfolio_type,
        )
        reporting_currency = SelectField(
            u"Reporting Currency",
            choices=currency_choices,
            default=portfolio.reporting_currency,
        )
        benchmark = StringField(
            u"Benchmark",
            [DataRequired(), Ticker()],
            default=portfolio.benchmark.symbol.symbol,
        )

    return EditPortfolioForm

src/views/alert.py
"""Alert endpoints"""

from typing import Union
from flask import Blueprint, url_for, render_template, redirect, flash
from flask_login import login_required, current_user

from src.forms import AddAlertForm, AddMarketWatchInstrument
from src.environment import User, MarketAlert, WatchListInstrument
from src.market import Instrument, Symbol, get_instrument
from src.market.ref_data import up, down, up_equal, down_equal
from src.market.signal import (
    Signal,
    DailyPortfolioReturnSignal,
    DailyReturnSignal,
    PriceSignal,
    LimitReturnSignal,
    PortfolioValueSignal,
)


alert_blueprint = Blueprint("alert", __name__, url_prefix="/alert")


@alert_blueprint.route("/list", methods=["GET"])
@login_required
def list_alerts():
    """List alerts."""

    user: User = current_user
    return render_template("alert/list_alerts.html", alerts=user.market_alerts)


@alert_blueprint.route("/add_alert", methods=["GET", "POST"])
@login_required
def add_alert():
    """Add new alert."""

    user: User = current_user
    alert_form = AddAlertForm()

    if alert_form.validate_on_submit():
        signal = get_signal(
            alert_form.signal.data,
            alert_form.underlying.data,
            alert_form.operator.data,
            alert_form.target.data,
            alert_form.start_date.data,
        )

        if signal not in [alert.signal for alert in user.market_alerts]:
            user.add_market_alert(MarketAlert(signal))
            return redirect(url_for("alert.list_alerts"))
        flash("Market alert already exists, please activate it.", "danger")

    return render_template("alert/add_alert.html", form=alert_form)


@alert_blueprint.route("/deactivate_alert/<int:alert_id>", methods=["GET"])
@login_required
def deactivate_alert(alert_id):
    """Deactivate alert."""

    alert = MarketAlert.find_by_id(alert_id)
    alert.deactivate()
    return redirect(url_for("alert.list_alerts"))


@alert_blueprint.route("/activate_alert/<int:alert_id>", methods=["GET"])
@login_required
def activate_alert(alert_id):
    """Activate alert."""

    alert = MarketAlert.find_by_id(alert_id)
    alert.activate()
    return redirect(url_for("alert.list_alerts"))


@alert_blueprint.route("/delete_alert/<int:alert_id>", methods=["GET"])
@login_required
def delete_alert(alert_id):
    """Delete alert."""

    alert = MarketAlert.find_by_id(alert_id)
    alert.delete_from_db()
    return redirect(url_for("alert.list_alerts"))


@alert_blueprint.route("/watchlist", methods=["GET", "POST"])
@login_required
def list_watchlist():
    """List alert."""

    user: User = current_user
    form = AddMarketWatchInstrument()

    if form.validate_on_submit():
        watchlist_inst = WatchListInstrument(get_instrument(Symbol(form.symbol.data)))
        user.add_watchlist_instrument(watchlist_inst)
        return redirect(url_for("alert.list_watchlist"))

    return render_template(
        "alert/watchlist.html", instruments=user.watch_list, form=form
    )


@alert_blueprint.route("/delete_watchlist/<int:inst_id>", methods=["GET"])
@login_required
def delete_watchlist_instrument(inst_id):
    """Delete watchlist instrument."""

    watchlist_inst = WatchListInstrument.find_by_id(inst_id)
    watchlist_inst.delete_from_db()
    return redirect(url_for("alert.list_watchlist"))


def get_signal(
    signal: str, underlying: Union[Instrument, str], operator, target, start_date
) -> Signal:
    """Get underlying portfolio or instrument."""

    operator_dict = {
        "Up": up,
        "Up or Equal": up_equal,
        "Down": down,
        "Down or Equal": down_equal,
    }
    operator = operator_dict[operator]
    signal_dict = {
        "Price Signal": lambda: PriceSignal(
            get_instrument(Symbol(underlying)), operator, target
        ),
        "Daily Return Signal": lambda: DailyReturnSignal(
            get_instrument(Symbol(underlying)), operator, target
        ),
        "Limit Return Signal": lambda: LimitReturnSignal(
            get_instrument(Symbol(underlying)), operator, target, start_date
        ),
        "Portfolio Value Signal": lambda: PortfolioValueSignal(
            underlying, operator, target
        ),
        "Daily Portfolio Return Signal": lambda: DailyPortfolioReturnSignal(
            underlying, operator, target
        ),
    }

    func = signal_dict[signal]
    return func()

src/views/home.py
"""Home endpoints"""

from datetime import datetime
from flask import Blueprint, render_template

from src.extensions import db

from src.environment import User, Portfolio, Position, Order
from src.market import SingleValue
from src.market.ref_data import buy, usd_ccy, cad_ccy, aapl, ry_to


home_blueprint = Blueprint("home", __name__)


@home_blueprint.route("/", methods=["GET"])
def home():
    """Home."""
    return render_template("home.html")


@home_blueprint.before_app_first_request
def add_user_guest():
    """Add guest user data."""

    email = "guest_user@gmail.com"
    password = "1234"

    db.create_all()
    if not User.find_by_email(email):

        # Create objects
        user = User(email, password)
        portfolio = Portfolio("My portfolio 1")
        position_1 = Position(aapl)
        position_2 = Position(ry_to)
        order_1 = Order(10, buy, SingleValue(100, usd_ccy), datetime(2021, 1, 5))
        order_2 = Order(15, buy, SingleValue(100, cad_ccy), datetime(2021, 2, 15))

        # Link and save objects
        user.save_to_db()
        user.confirm_user()
        user.add_portfolio(portfolio)
        portfolio.add_position(position_1)
        portfolio.add_position(position_2)
        position_1.add_order(order_1)
        position_2.add_order(order_2)

src/views/portfolio.py
"""Portfolio endpoints"""

from flask import Blueprint, url_for, render_template, redirect, flash
from flask_login import login_required, current_user
from flask_wtf import FlaskForm

from src.environment import Portfolio
from src.market import Symbol, Currency, get_instrument
from src.forms.portfolio import AddPortfolioForm, generate_edit_portfolio_form


portfolio_blueprint = Blueprint("portfolio", __name__, url_prefix="/portfolio")


@portfolio_blueprint.route("/list", methods=["GET"])
@login_required
def list_portfolios():
    """List portfolios of the user including current market values."""

    portfolios = current_user.portfolios
    portfolios.sort(key=lambda x: x.primary, reverse=True)

    if not portfolios:
        flash("Add a custom portfolio!")

    return render_template("portfolio/list_portfolios.html", portfolios=portfolios)


@portfolio_blueprint.route("/add_portfolio", methods=["GET", "POST"])
@login_required
def add_portfolio():
    """Add a new portfolio."""

    form = AddPortfolioForm()
    if form.validate_on_submit():

        symbol = Symbol(form.benchmark.data)
        security = get_instrument(symbol)
        currency = Currency(form.reporting_currency.data)

        portfolio = Portfolio(
            form.port_name.data,
            form.port_type.data,
            currency,
            security,
        )
        current_user.add_portfolio(portfolio)

        if current_user.get_primary_portfolio() is None:
            portfolio.set_as_primary()
        return redirect(url_for("portfolio.list_portfolios"))
    return render_template("portfolio/add_portfolio.html", form=form)


@portfolio_blueprint.route("/edit/<int:portfolio_id>", methods=["GET", "POST"])
@login_required
def edit_portfolio(portfolio_id):
    """Edit an existing portfolio."""

    port = Portfolio.find_by_id(portfolio_id)
    edit_form = generate_edit_portfolio_form(port)
    form: FlaskForm = edit_form()
    if form.validate_on_submit():
        symbol = Symbol(form.benchmark.data)
        security = get_instrument(symbol)
        currency = Currency(form.reporting_currency.data)
        port.edit(
            form.port_name.data,
            currency,
            form.port_type.data,
            security,
        )
        return redirect(url_for("portfolio.list_portfolios"))
    return render_template(
        "portfolio/edit_portfolio.html", form=form, portfolio_id=portfolio_id
    )


@portfolio_blueprint.route("/delete/<int:portfolio_id>", methods=["GET"])
@login_required
def delete_portfolio(portfolio_id):
    """Delete an existing portfolio along with its positions as well as orders."""

    port = Portfolio.find_by_id(portfolio_id)
    port.delete_from_db()
    return redirect(url_for("portfolio.list_portfolios"))


@portfolio_blueprint.route("/set_primary/<int:portfolio_id>", methods=["GET"])
@login_required
def set_portfolio_primary(portfolio_id):
    """Set a portfolio primary which will be viewed at the top when listing portfolios."""

    primary_portfolio: Portfolio = current_user.get_primary_portfolio()

    if primary_portfolio:
        primary_portfolio.primary = False

    current_portfolio = Portfolio.find_by_id(portfolio_id)
    current_portfolio.set_as_primary()

    return redirect(url_for("portfolio.list_portfolios"))


@portfolio_blueprint.route("/activate_daily_report/<int:portfolio_id>", methods=["GET"])
@login_required
def activate_daily_report(portfolio_id):
    """Activate daily report for a given portfolio."""

    port = Portfolio.find_by_id(portfolio_id)
    port.daily_report.activate()

    return redirect(url_for("portfolio.list_portfolios"))


@portfolio_blueprint.route(
    "/deactivate_daily_report/<int:portfolio_id>", methods=["GET"]
)
@login_required
def deactivate_daily_report(portfolio_id):
    """Activate daily report for a given portfolio."""

    port = Portfolio.find_by_id(portfolio_id)
    port.daily_report.deactivate()

    return redirect(url_for("portfolio.list_portfolios"))

src/views/report.py
"""Dashboard endpoints"""

from flask import Blueprint, url_for, redirect
from flask_login import current_user, login_required


report_blueprint = Blueprint("report", __name__, url_prefix="/report")


@report_blueprint.route("/report/", methods=["GET"])
@login_required
def view_report():
    """Direct user to dashboard."""
    empty_port_check = [bool(port.positions) for port in current_user.portfolios]

    if any(empty_port_check):
        return redirect("/report/")
    return redirect(url_for("portfolio.list_portfolios"))

src/views/user.py
"""User endpoints"""

# pylint: disable=no-value-for-parameter, bare-except
import os

from flask import Blueprint, url_for, render_template, redirect, flash
from flask_login import login_user, logout_user
from itsdangerous import URLSafeTimedSerializer

from src.environment.user import User
from src.forms.user import RegisterForm, LoginForm
from src.tasks.email import send_email


user_blueprint = Blueprint("users", __name__, url_prefix="/users")


@user_blueprint.route("/login", methods=["GET", "POST"])
def login():
    """Log in user."""
    form = LoginForm()
    if form.validate_on_submit():
        user = User.find_by_email(form.email.data)
        login_user(user)
        return redirect(url_for("portfolio.list_portfolios"))
    return render_template("user/login.html", form=form)


@user_blueprint.route("/register", methods=["GET", "POST"])
def register():
    """Register user and send a confirmation email."""
    form = RegisterForm()
    if form.validate_on_submit():
        new_user = User(form.email.data, form.password.data)
        new_user.save_to_db()

        token = generate_confirmation_token(new_user.email)
        confirm_url = url_for("users.confirm_email", token=token, _external=True)

        send_email(
            subject="Account confirmation - Portfolio Engineer",
            recipients=[new_user.email],
            html=render_template(
                "email/account_confirmation.html", confirm_url=confirm_url
            ),
        )

        flash("You have confirmed your account. Thanks!", "success")
        return redirect(url_for("users.login"))
    return render_template("user/register.html", form=form)


@user_blueprint.route("/confirm/<string:token>", methods=["GET"])
def confirm_email(token):
    """Confirm user."""
    email = confirm_token(token)

    if email:
        user = User.find_by_email(email)
        user.confirm_user()
        user.save_to_db()
        flash("You have confirmed your account. Thanks!", "success")
    else:
        flash("The confirmation link is invalid or has expired.", "danger")
    return redirect(url_for("users.login"))


@user_blueprint.route("/guest", methods=["GET", "POST"])
def guest():
    """Guest user."""
    login_user(User.find_by_email("guest_user@gmail.com"))
    return redirect(url_for("portfolio.list_portfolios"))


@user_blueprint.route("/logout", methods=["GET", "POST"])
def logout():
    """Log out user."""
    logout_user()
    return redirect(url_for("home.home"))


def generate_confirmation_token(email: str) -> str:
    """Generate token to be sent to the new user for registering."""
    serializer = URLSafeTimedSerializer(os.environ.get("SECRET_KEY"))
    return serializer.dumps(email, salt=os.environ.get("SECURITY_PASSWORD_SALT"))


def confirm_token(token, expiration=3600):
    """Use serializer to parse the token and to confirm the new user."""
    serializer = URLSafeTimedSerializer(os.environ.get("SECRET_KEY"))
    try:
        email = serializer.loads(
            token, salt=os.environ.get("SECURITY_PASSWORD_SALT"), max_age=expiration
        )
    except:
        return None
    return email

src/templates/base/account.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
        integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">

    <title>Portfolio Engineer</title>
</head>
<header>
    <nav class="navbar navbar-default navbar-static-top navbar-expand-lg bg-success">
        <div class="container">
            <a class="navbar-brand text-white" href="">Portfolio Engineer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link text-white" href="{{ url_for('account.list_portfolios') }}">My
                        Account</a>
                    <a class="nav-item nav-link text-white" href="{{ url_for('account.update_portfolio_list') }}">Sync
                        Portfolios</a>
                    <a class="nav-item nav-link text-white" href="{{ url_for('account.add_portfolio') }}">Add Custom
                        Portfolio</a>
                    <a class="nav-item nav-link text-white" href="{{ url_for('users.log_out_user') }}">Log out</a>
                </div>
            </div>
        </div>
    </nav>
</header>

<body>
    {% block content %}

    {% endblock %}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js"
        integrity="sha384-BOsAfwzjNJHrJ8cZidOg56tcQWfp6y72vEJ8xQ9w6Quywb24iOsW913URv1IS4GD"
        crossorigin="anonymous"></script>
</body>

</html>

src/templates/base/home.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
        integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">

    <title>Portfolio Engineer</title>
</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-success">
        <div class="container">
            <a class="navbar-brand text-white" href="{{ url_for('home.home') }}">Portfolio Engineer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link text-white" id="LogIn" href="{{ url_for('users.login') }}">Log
                        in</a>
                    <a class="nav-item nav-link text-white" href="{{ url_for('users.register') }}">Sign up</a>
                    <a class="nav-item nav-link text-white" id="Guest" href="{{ url_for('users.guest') }}">Guest</a>
                </div>
            </div>
        </div>
    </nav>
</header>

<body>
    {% block content %}

    {% endblock %}
    <footer class="bg-light text-center text-lg-start fixed-bottom">
        <div class="container">
            <span class="text-muted"> Portfolio Engineer</span>
        </div>
    </footer>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js"
        integrity="sha384-BOsAfwzjNJHrJ8cZidOg56tcQWfp6y72vEJ8xQ9w6Quywb24iOsW913URv1IS4GD"
        crossorigin="anonymous"></script>
</body>

</html>

src/templates/base/portfolio.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Portfolio Engineer</title>
</head>
<header>
    <nav class="navbar navbar-default navbar-static-top navbar-expand-lg bg-success">
        <div class="container">
            <a class="navbar-brand text-white" href="{{ url_for('portfolio.list_portfolios') }}">Portfolio Engineer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link text-white"
                        href="{{ url_for('portfolio.list_portfolios') }}">Portfolios</a>
                    <a class="nav-item nav-link text-white" href="{{ url_for('portfolio.add_portfolio') }}">Add
                        Portfolio</a>
                    <a class="nav-item nav-link text-white" href="{{ url_for('alert.list_alerts') }}">Alerts</a>
                    <a class="nav-item nav-link text-white" href="{{ url_for('alert.add_alert') }}">Add Alert</a>
                    <a class="nav-item nav-link text-white" href="{{ url_for('alert.list_watchlist') }}">Watchlist</a>
                    <a class="nav-item nav-link text-white" href="{{ url_for('report.view_report') }}">Dashboard</a>
                    <a class="nav-item nav-link text-white" href="{{ url_for('users.logout') }}">Log out</a>
                </div>
            </div>
        </div>
    </nav>
</header>

<body>
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
</body>

</html>