src/views/order.py
"""Order endpoints"""

from flask import Blueprint, url_for, render_template, redirect
from flask_login import login_required
from flask_wtf import FlaskForm

from src.environment import Portfolio, Position, Order
from src.forms.order import AddOrderForm, generate_edit_order_form
from src.market import Symbol, SingleValue, get_instrument, DIRECTION_MAP

order_blueprint = Blueprint("order", __name__, url_prefix="/order")


@order_blueprint.route("/delete_order/<int:order_id>", methods=["GET"])
@login_required
def delete_order(order_id: int):
    """Delete an order."""

    order = Order.find_by_id(order_id)
    position = order.position
    order.delete_from_db()
    if not position.orders:
        position.delete_from_db()
    return redirect(url_for("portfolio.list_portfolios"))


@order_blueprint.route("/edit/<int:order_id>", methods=["GET", "POST"])
@login_required
def edit_order(order_id: int):
    """Edit an order."""
    order = Order.find_by_id(order_id)
    edit_form = generate_edit_order_form(order)
    form: FlaskForm = edit_form()
    if form.validate_on_submit():
        order.edit(
            form.quantity.data,
            DIRECTION_MAP[form.direction.data],
            SingleValue(form.cost.data, order.cost.currency),
            form.exec_datetime.data,
        )
        return redirect(url_for("portfolio.list_portfolios"))
    return render_template("order/edit_order.html", form=form, order_id=order_id)


@order_blueprint.route("/<int:portfolio_id>/add_order", methods=["GET", "POST"])
@login_required
def add_order(portfolio_id):
    """Add order."""

    form = AddOrderForm()
    if form.validate_on_submit():
        symbol = Symbol(form.symbol.data)
        instrument = get_instrument(symbol)
        port = Portfolio.find_by_id(portfolio_id)
        pos = port.get_position_by_symbol(symbol) or port.add_position(
            Position(instrument)
        )
        order = Order(
            form.quantity.data,
            DIRECTION_MAP[form.direction.data],
            SingleValue(form.cost.data, instrument.asset_currency),
            form.exec_datetime.data,
        )
        pos.add_order(order)
        return redirect(url_for("portfolio.list_portfolios"))
    return render_template("order/add_order.html", form=form, portfolio_id=portfolio_id)

src/views/position.py
"""Position endpoints"""

from datetime import date
from flask import Blueprint, url_for, render_template, redirect
from flask_login import login_required

from src.environment import Position, Order
from src.market.utils import get_business_day
from src.market.ref_data import buy, sell


position_blueprint = Blueprint("position", __name__, url_prefix="/position")


@position_blueprint.route("/<int:position_id>/details", methods=["GET"])
@login_required
def position_details(position_id):
    """Get position details."""

    return render_template(
        "position/position_details.html",
        position=Position.find_by_id(position_id),
    )


@position_blueprint.route("/<int:position_id>/close", methods=["GET"])
@login_required
def close_position(position_id):
    """Close existing position by adding closing order."""

    position = Position.find_by_id(position_id)

    if position.is_open:
        order = Order(
            position.open_quantity,
            sell if position.open_quantity > 0 else buy,
            position.security.value(raw=True),
            get_business_day(date.today()),
        )
        position.add_order(order)

    return redirect(url_for("portfolio.list_portfolios"))

src/templates/position/position_details.html
{% extends "base/portfolio.html" %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-success">
        Position details:
    </h2>

</div>

<div class="container mt-4 mb-3">
    <div class="card">
        <h5 class="card-header">

            <div class="row">
                <div class="col-8">
                    Symbol: {{ position.security.symbol }}
                </div>
            </div>
        </h5>
        <div class="row">
            <div class="col-12">
                <div class="card-body">

                    <p class="card-text">Instrument type: {{ position.security.security_type }}</p>
                    <p class="card-text">Name: {{ position.security.name }}</p>
                    <p class="card-text">Current price: {{ position.security.value() }}</p>
                    <p class="card-text">Total position value: {{ position.current_value() }}</p>

                    <div class="card">

                        <h6 class="card-header">
                            Orders
                        </h6>

                        <div class="card-body">

                            <table class="table">
                                <thead>
                                    <tr class="text-center">
                                        <th scope="col">Execution Time</th>
                                        <th scope="col">Quantity</th>
                                        <th scope="col">Cost</th>
                                        <th scope="col">Direction</th>
                                        <th scope="col">Actions</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in position.orders %}
                                    <tr class="text-center">

                                        <td class="align-middle">{{ order.time }}</td>
                                        <td class="align-middle">{{ order.quantity }}</td>
                                        <td class="align-middle">{{ order.cost }}</td>
                                        <td class="align-middle">{{ order.direction}}</td>

                                        <td class="align-middle">

                                            <a href="{{ url_for('order.edit_order', order_id=order.id) }}"
                                                class="btn btn-outline-success">Edit Order</a>
                                            <a href="{{ url_for('order.delete_order', order_id=order.id) }}"
                                                class="btn btn-outline-danger">Delete Order</a>

                                        </td>

                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}